# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QPlay' do

  use_frameworks!

  pod 'GoogleSignIn'
  pod 'Firebase/Auth'

  target 'QPlayTests' do
    inherit! :search_paths

  end

  target 'QPlayUITests' do

  end

end
