# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QPlay' do

  use_frameworks!

  pod 'GoogleSignIn'
  pod 'Firebase/Auth'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'ObjectMapper', '~> 3.5'
  pod 'Alamofire'
  pod 'Kingfisher', '~> 7.0'

  target 'QPlayTests' do
    inherit! :search_paths

  end

  target 'QPlayUITests' do

  end

end
